# Generated by Django 6.0.8 on 2026-09-25 05:14

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PYTHON', 'Python'), ('DATA_SCIENCE', 'Data Science'), ('ML', 'Machine Learning'), ('DL', 'Deep Learning'), ('AI', 'AI'), ('GENAI', 'GenAI'), ('DJANGO', 'Django'), ('ANALYTICS', 'Data Analytics'), ('WEB', 'Web Development')], db_index=True, max_length=20)),
                ('summary', models.CharField(help_text='Short description shown on cards', max_length=300)),
                ('cover_image', models.ImageField(blank=True, upload_to='projects/covers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif', 'svg']), apps.core.validators.MaxFileSizeValidator(10), apps.core.validators.FileSignatureValidator()])),
                ('problem_statement', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('dataset', models.TextField(blank=True)),
                ('architecture', models.TextField(blank=True)),
                ('data_flow', models.TextField(blank=True)),
                ('implementation', models.TextField(blank=True)),
                ('algorithm', models.TextField(blank=True, verbose_name='Machine learning algorithm')),
                ('model_training', models.TextField(blank=True)),
                ('evaluation', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('future_improvements', models.TextField(blank=True)),
                ('documentation', models.TextField(blank=True)),
                ('pipeline_steps', models.JSONField(blank=True, default=list, help_text='Ordered steps for the architecture diagram, e.g. ["Dataset", "Data Cleaning", "EDA"]')),
                ('documentation_pdf', models.FileField(blank=True, upload_to='projects/docs/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.core.validators.MaxFileSizeValidator(25), apps.core.validators.FileSignatureValidator()])),
                ('model_3d', models.FileField(blank=True, help_text='Optional GLB/GLTF/OBJ', upload_to='projects/models/', validators=[django.core.validators.FileExtensionValidator(['glb', 'gltf', 'obj']), apps.core.validators.MaxFileSizeValidator(50), apps.core.validators.FileSignatureValidator()])),
                ('github_url', models.URLField(blank=True)),
                ('live_demo_url', models.URLField(blank=True)),
                ('demo_video_url', models.URLField(blank=True, help_text='YouTube/Vimeo or direct video URL')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_sample', models.BooleanField(default=False, help_text='Marks demo content to be replaced')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(default='python', max_length=30)),
                ('code', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/screenshots/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif', 'svg']), apps.core.validators.MaxFileSizeValidator(10), apps.core.validators.FileSignatureValidator()])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video', models.FileField(blank=True, upload_to='projects/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov']), apps.core.validators.MaxFileSizeValidator(200), apps.core.validators.FileSignatureValidator()])),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.technology'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'category'], name='projects_pr_is_publ_ef79a9_idx'),
        ),
    ]
