# Generated by Django 6.0.8 on 2026-09-25 05:14

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('score', models.CharField(blank=True, help_text='Percentage or CGPA', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('JOB', 'Job'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('VOLUNTEER', 'Volunteer')], default='JOB', max_length=15)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current', null=True)),
                ('description', models.TextField(blank=True, help_text='Markdown; use bullet points for responsibilities')),
                ('technologies', models.CharField(blank=True, help_text='Comma separated', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='Your Name', max_length=150)),
                ('headline', models.CharField(default='AI / Data Science / Python Developer', max_length=200)),
                ('tagline', models.TextField(default='I build intelligent applications, machine learning solutions, data-driven systems, and modern web applications.')),
                ('short_bio', models.TextField(blank=True)),
                ('about', models.TextField(blank=True, help_text='Markdown')),
                ('career_objective', models.TextField(blank=True)),
                ('technical_interests', models.TextField(blank=True, help_text='One per line')),
                ('current_learning', models.TextField(blank=True, help_text='One per line')),
                ('professional_goals', models.TextField(blank=True)),
                ('hero_badges', models.CharField(default='Python,Machine Learning,Deep Learning,Data Science,SQL,Django,GenAI', help_text='Comma separated', max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif', 'svg']), apps.core.validators.MaxFileSizeValidator(10), apps.core.validators.FileSignatureValidator()])),
                ('resume_pdf', models.FileField(blank=True, upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.core.validators.MaxFileSizeValidator(25), apps.core.validators.FileSignatureValidator()])),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming'), ('DATA_SCIENCE', 'Data Science'), ('MACHINE_LEARNING', 'Machine Learning'), ('DEEP_LEARNING', 'Deep Learning'), ('DATABASE', 'Database'), ('WEB', 'Web Development'), ('ANALYTICS', 'Data Analytics'), ('GENAI', 'Generative AI'), ('AGENTIC_AI', 'Agentic AI'), ('TOOLS', 'Tools & Cloud')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('proficiency_label', models.CharField(blank=True, max_length=40)),
                ('proficiency_percent', models.PositiveSmallIntegerField(blank=True, help_text='Optional 0-100', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon key, e.g. python, database, brain', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
