# Generated by Django 6.0.8 on 2026-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, help_text='Leave blank if unknown', null=True),
        ),
    ]
