# Generated by Django 6.0.8 on 2026-09-25 05:14

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=150)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(help_text='Used in the verification URL: /certificate/<credential_id>', max_length=100, unique=True)),
                ('credential_url', models.URLField(blank=True, help_text='Official verification link from the provider')),
                ('image', models.ImageField(blank=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif', 'svg']), apps.core.validators.MaxFileSizeValidator(10), apps.core.validators.FileSignatureValidator()])),
                ('pdf', models.FileField(blank=True, upload_to='certificates/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf']), apps.core.validators.MaxFileSizeValidator(25), apps.core.validators.FileSignatureValidator()])),
                ('description', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, help_text='Comma separated', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-issue_date'],
            },
        ),
    ]
