# Generated by Django 6.0.8 on 2026-09-25 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=10)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=10, help_text='0 = no time limit')),
                ('show_leaderboard', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='learning.studycategory')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('MCQ', 'Multiple choice'), ('CODING', 'Coding'), ('OUTPUT', 'Output prediction'), ('SQL', 'SQL query'), ('DEBUGGING', 'Debugging'), ('THEORY', 'Theory')], default='MCQ', max_length=10)),
                ('prompt', models.TextField(help_text='Markdown')),
                ('code', models.TextField(blank=True, help_text='Code shown with the question')),
                ('code_language', models.CharField(default='python', max_length=30)),
                ('options', models.JSONField(blank=True, default=list, help_text='MCQ options, e.g. ["list", "tuple", "dict"]')),
                ('correct_option', models.PositiveSmallIntegerField(blank=True, help_text='0-based index for MCQ', null=True)),
                ('accepted_answers', models.JSONField(blank=True, default=list, help_text='Accepted text answers (case/whitespace-insensitive). Empty = self-review.')),
                ('explanation', models.TextField(blank=True, help_text='Markdown')),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('timed_out', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['quiz', '-percent'], name='quizzes_qui_quiz_id_bec7b3_idx')],
            },
        ),
    ]
